{{ config(materialized='table', alias='D_CALENDAR') }}

SELECT 
    {{ hash(['DATE_DT'])}} AS DATE_ID, 
    DATE_DT, 
    DATE_CODE AS DATE_CD, 
    DAY_CODE AS DAY_CD, 
    DATE_DESC AS DATE_DS, 
    DAY_DESC AS DAY_DS, 
    WEEK_CODE AS WEEK_CD, 
    WEEK_DESC AS WEEK_DS, 
    MONTH_CODE AS MONTH_CD, 
    MONTH_DESC AS MONTH_DS, 
    YEAR_CODE AS YEAR_CD, 
    QUARTER_CODE AS QUARTER_CD, 
    HALF_CODE AS HALF_CD, 
    CURRENT_TIMESTAMP() AS TRANSACTION_TIMESTAMP, 
    'I' AS TRANSACTION_FLAG 
FROM {{ ref('CALENDAR__ODS') }}