{{ config(materialized='table', alias='D_CLIENT') }}

SELECT DISTINCT
    {{hash(['ORDERS.CLIENT_COD'])}} AS CLIENT_ID, 
    ORDERS.CLIENT_COD AS CLIENT_CD,
    ORDERS.CLIENT_NAME AS CLIENT_DS, 
    ORDERS.CLIENT_SEGMENT AS CLIENT_SEGMENT_DS,
    ADDRESS.ADDRESS_ID AS CLIENT_ADDRESS_ID, 
    CURRENT_TIMESTAMP() AS TRANSACTION_TIMESTAMP, 
    'I' AS TRANSACTION_FLAG 
FROM {{ ref('ORDER__ODS') }} AS ORDERS
LEFT OUTER JOIN {{ ref('D_ADDRESS__DWH') }} AS ADDRESS
    ON ORDERS.CLIENT_ADDRESS_COD = ADDRESS.ADDRESS_CD