{{ config(materialized='table', alias='D_MANAGER') }}

SELECT 
    {{hash(['REGION', 'MARKET'])}} AS REGIONAL_MANAGER_ID, 
    REGION AS REGION_DS, 
    MARKET AS MARKET_DS, 
    PERSON AS PERSON_DS, 
    CURRENT_TIMESTAMP() AS TRANSACTION_TIMESTAMP, 
    'I' AS TRANSACTION_FLAG 
FROM {{ ref('REGIONALMANAGER__ODS') }}