{{ config(materialized='table', alias='D_PRODUCT') }}

SELECT DISTINCT
    {{ hash(['PRODUCT_COD']) }} AS PRODUCT_ID, 
    PRODUCT_COD AS PRODUCT_CD, 
    PRODUCT_NAME AS PRODUCT_DS, 
    CATEGORY AS CATEGORY_DS, 
    SUB_CATEGORY AS SUBCATEGORY_DS, 
    CURRENT_TIMESTAMP() AS TRANSACTION_TIMESTAMP, 
    'I' AS TRANSACTION_FLAG 
FROM {{ ref('ORDER__ODS') }}