{{ config(materialized='table', alias='F_ORDER') }}

SELECT
    {{ hash(['ORDERS.ROW_ID']) }} AS ORDER_ID,
    ORDERS.ORDER_COD AS ORDER_CD,
    ORDERS.PRODUCT_COD AS PRODUCT_CD,
    ORDERS.ORDER_PRIORITY AS ORDER_PRIORITY_DS,
    ORDERS_CALENDAR.DATE_ID AS ORDER_DATE_ID,
    SHIPMENT_CALENDAR.DATE_ID AS SHIPMENT_DATE_ID,
    ORDERS.SHIP_MODE AS SHIPMENT_MODE_DS,
    ADDRESS.ADDRESS_ID AS SHIPMENT_ADDRESS_ID,
    CLIENT.CLIENT_ID AS CLIENT_ID,
    MANAGER.REGIONAL_MANAGER_ID,
    PRODUCT.PRODUCT_ID,
    CASE WHEN RETURNED.PRODUCT_COD IS NULL THEN 0 ELSE 1 END AS RETURNED_FL,
    ORDERS.QUANTITY AS QTY,
    ORDERS.SALES AS SALES_VL,
    ORDERS.DISCOUNT AS DISCOUNT_VL,
    ORDERS.PROFIT AS PROFIT_VL,
    ORDERS.SHIPPING_COST AS SHIPPING_COST_VAL,
    CURRENT_TIMESTAMP() AS TRANSACTION_TIMESTAMP,
    'I' AS TRANSACTION_FLAG
FROM {{ ref('ORDER__ODS') }} AS ORDERS
LEFT JOIN {{ ref('D_CALENDAR__DWH') }} AS ORDERS_CALENDAR
    ON ORDERS.ORDER_DATE = ORDERS_CALENDAR.DATE_DT
LEFT JOIN {{ ref('D_CALENDAR__DWH') }} AS SHIPMENT_CALENDAR
    ON ORDERS.SHIP_DATE = SHIPMENT_CALENDAR.DATE_DT
LEFT JOIN {{ ref('D_ADDRESS__DWH') }} AS ADDRESS
    ON ORDERS.SHIPMENT_ADDRESS_COD = ADDRESS.ADDRESS_CD
LEFT JOIN {{ ref('D_CLIENT__DWH') }} AS CLIENT
    ON ORDERS.CLIENT_COD = CLIENT.CLIENT_CD
LEFT JOIN {{ ref('D_PRODUCT__DWH') }} AS PRODUCT
    ON ORDERS.PRODUCT_COD = PRODUCT.PRODUCT_CD
LEFT JOIN {{ ref('RETURN__ODS') }} AS RETURNED
    ON ORDERS.ORDER_COD = RETURNED.ORDER_COD
    AND ORDERS.PRODUCT_COD = RETURNED.PRODUCT_COD 
LEFT JOIN {{ ref('D_MANAGER__DWH') }} AS MANAGER
    ON ORDERS.MARKET = MANAGER.MARKET_DS
    AND ORDERS.REGION = MANAGER.REGION_DS