{{ config(materialized='table', alias='ODS_CALENDAR') }}

SELECT 
    CAST(DATE_DT AS DATE) AS DATE_DT,
    PARSE_DATE('%Y%m%d', CAST(DATE_CODE AS STRING)) AS DATE_CODE,
    CAST(DAY_CODE AS NUMERIC) AS DAY_CODE,
    TRIM(CAST(DATE_DESC AS STRING)) AS DATE_DESC,
    TRIM(CAST(DAY_DESC AS STRING)) AS DAY_DESC,
    CAST(WEEK_CODE AS NUMERIC) AS WEEK_CODE,
    TRIM(CAST(WEEK_DESC AS STRING)) AS WEEK_DESC,
    CAST(MONTH_CODE AS NUMERIC) AS MONTH_CODE,
    TRIM(CAST(MONTH_DESC AS STRING)) AS MONTH_DESC,
    CAST(YEAR_CODE AS NUMERIC) AS YEAR_CODE,
    TRIM(CAST(QUARTER_CODE AS STRING)) AS QUARTER_CODE,
    TRIM(CAST(HALF_CODE AS STRING)) AS HALF_CODE
FROM {{ ref('calendar') }}